// Code generated by gen-cobra-flags. DO NOT EDIT.
package example

import (
	"github.com/spf13/cobra"
)

// AddConfigFlags adds flags for Config to the cobra command
func AddConfigFlags(cmd *cobra.Command, config *Config) {
	cmd.Flags().StringVarP(&config.Host, "host", "H", "localhost", "Server host")
	cmd.Flags().IntVarP(&config.Port, "port", "p", 8080, "Server port")
	cmd.Flags().BoolVarP(&config.Debug, "debug", "d", false, "Enable debug mode")
	cmd.Flags().BoolVarP(&config.Verbose, "verbose", "v", false, "Enable verbose logging")
	cmd.Flags().StringVarP(&config.LogLevel, "log-level", "l", "info", "Log level (info, warn, error)")
}
