// Package adaptors provides the runtime conversion functions used by code
// generated by gen-cobra-flags. It maps between the string-oriented values
// supplied on the command line and the strongly typed fields of the target
// struct (IPs, durations, timestamps, numbers, slices, maps, and so on).
package adaptors

import (
	"encoding/json"
	"fmt"
	"net"
	"os"
	"regexp"
	"strconv"
	"time"

	"go.yaml.in/yaml/v3"
)

// ResolveConfigInput resolves the raw bytes to decode for a struct-level config
// flag value. The value may be either a path to a JSON/YAML file or the literal
// JSON/YAML content itself:
//
//   - If cin is empty, it returns (nil, nil). No config was supplied; this is not
//     an error, and decoding nil yields a zero-valued config so downstream
//     required-flag checks still apply.
//   - If cin points to an existing regular file (absolute or relative to the
//     current working directory), the file's contents are returned.
//   - Otherwise cin is treated as literal inline JSON/YAML content and returned
//     as-is.
func ResolveConfigInput(cin string) ([]byte, error) {
	if cin == "" {
		return nil, nil
	}
	if info, err := os.Stat(cin); err == nil && !info.IsDir() {
		data, err := os.ReadFile(cin)
		if err != nil {
			return nil, fmt.Errorf("reading config file %q: %w", cin, err)
		}
		return data, nil
	}
	return []byte(cin), nil
}

// JsonOrYamlToStruct unmarshals data into a value of type T. If data is valid
// JSON it is decoded as JSON, otherwise it is decoded as YAML. It is used to
// hydrate a config struct from the value of the struct-level config flag.
func JsonOrYamlToStruct[T any](data []byte) (T, error) {
	var t T

	if json.Valid(data) {
		err := json.Unmarshal(data, &t)
		return t, err
	}

	err := yaml.Unmarshal(data, &t)
	return t, err
}

// IPToString formats an IP address using its standard textual representation.
func IPToString(ip net.IP) (string, error) {
	return ip.String(), nil
}

// StringToIP parses a textual IPv4 or IPv6 address. It returns a nil net.IP
// (without an error) if the input is not a valid address, matching the
// behavior of net.ParseIP.
func StringToIP(ip string) (net.IP, error) {
	return net.ParseIP(ip), nil
}

// TimeToString formats t as an RFC 3339 timestamp.
func TimeToString(t time.Time) (string, error) {
	return t.Format(time.RFC3339), nil
}

// StringToTime parses an RFC 3339 timestamp.
func StringToTime(t string) (time.Time, error) {
	return time.Parse(time.RFC3339, t)
}

// DurationToString formats a duration using time.Duration.String (e.g. "1h30m0s").
func DurationToString(dur time.Duration) (string, error) {
	return dur.String(), nil
}

// StringToDuration parses a Go duration string (e.g. "1h30m").
func StringToDuration(dur string) (time.Duration, error) {
	return time.ParseDuration(dur)
}

// IPNetToString formats a CIDR network in its standard "addr/mask" form.
func IPNetToString(ipnet *net.IPNet) (string, error) {
	return ipnet.String(), nil
}

// StringToIPNet parses a CIDR notation network (e.g. "10.0.0.0/24"). The
// host address bits are masked off, returning the network only.
func StringToIPNet(ipnet string) (*net.IPNet, error) {
	_, network, err := net.ParseCIDR(ipnet)

	return network, err
}

// StringToBool parses a boolean from common textual forms. It accepts
// "true"/"1"/"yes"/"on" as true and "false"/"0"/"no"/"off" as false; any other
// value yields false without an error.
func StringToBool(s string) (bool, error) {
	switch s {
	case "true", "1", "yes", "on":
		return true, nil
	case "false", "0", "no", "off":
		return false, nil
	default:
		return false, nil
	}
}

// BoolToString renders a boolean as "true" or "false".
func BoolToString(b bool) (string, error) {
	if b {
		return "true", nil
	}

	return "false", nil
}

// IntegerToString formats any integer type as a base-10 string.
func IntegerToString[IN Integer](i IN) (string, error) {
	return fmt.Sprintf("%d", i), nil
}

// StringToInteger parses a base-10 integer string into the requested integer
// type. It returns an error if the input is not a valid integer.
func StringToInteger[OUT Integer](s string) (OUT, error) {
	i, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		return 0, err
	}

	return OUT(i), nil
}

// Integer is the set of integer types supported by the numeric adaptors.
type Integer interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64 |
		~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~uintptr
}

// IntegerToInteger converts between two integer types via a numeric
// conversion. Overflow wraps following Go's conversion rules.
func IntegerToInteger[IN Integer, OUT Integer](i IN) (OUT, error) {
	return OUT(i), nil
}

// Float is the set of floating-point types supported by the numeric adaptors.
type Float interface {
	~float32 | ~float64
}

// FloatToFloat converts between two floating-point types.
func FloatToFloat[IN Float, OUT Float](f IN) (OUT, error) {
	return OUT(f), nil
}

// FloatToString formats a floating-point value using the %f verb.
func FloatToString[IN Float](f IN) (string, error) {
	return fmt.Sprintf("%f", f), nil
}

// StringToFloat parses a floating-point string into the requested float type.
// It returns an error if the input is not a valid number.
func StringToFloat[OUT Float](s string) (OUT, error) {
	f, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return 0, err
	}

	return OUT(f), nil
}

// FloatToInteger converts a float to an integer by truncation toward zero.
func FloatToInteger[IN Float, OUT Integer](f IN) (OUT, error) {
	return OUT(f), nil
}

// IntegerToFloat converts an integer to a floating-point value.
func IntegerToFloat[IN Integer, OUT Float](i IN) (OUT, error) {
	return OUT(i), nil
}

// BoolToInteger maps true to 1 and false to 0 in the requested integer type.
func BoolToInteger[OUT Integer](b bool) (OUT, error) {
	if b {
		return OUT(1), nil
	}

	return OUT(0), nil
}

// IntegerToBool reports whether i is non-zero.
func IntegerToBool[IN Integer](i IN) (bool, error) {
	if i != 0 {
		return true, nil
	}

	return false, nil
}

// SliceToSlice applies f to every element of in and returns a new slice of the
// results, preserving order. It stops and returns the first error encountered.
func SliceToSlice[IN any, OUT any](f func(IN) (OUT, error), in []IN) ([]OUT, error) {
	out := make([]OUT, len(in))
	for i := range in {
		o, err := f(in[i])
		if err != nil {
			return nil, err
		}

		out[i] = o
	}

	return out, nil
}

// StringMapToStringMap applies f to every value of in, returning a new map with
// the same keys. It stops and returns the first error encountered.
func StringMapToStringMap[IN any, OUT any](f func(IN) (OUT, error), in map[string]IN) (map[string]OUT, error) {
	out := make(map[string]OUT)
	for i := range in {
		o, err := f(in[i])
		if err != nil {
			return nil, err
		}

		out[i] = o
	}

	return out, nil
}

// ToPtr returns a pointer to a copy of t. It is used to adapt a value flag into
// a pointer field on the target struct.
func ToPtr[T any](t T) (*T, error) {
	return &t, nil
}

// StringToStruct unmarshals a single JSON or YAML string into a value of type
// T. It is used to adapt a string flag into a struct (or pointer-to-struct)
// field on the config struct that has no dedicated CLI representation.
func StringToStruct[T any](s string) (T, error) {
	return JsonOrYamlToStruct[T]([]byte(s))
}

// StringSliceToStructSlice unmarshals each element of in (a repeatable string
// flag where every value is JSON or YAML) into a value of type T, returning the
// resulting slice. It is used to adapt a StringSlice flag into a []T or []*T
// field that has no dedicated CLI representation. A nil/empty input yields a nil
// slice so the field is left unset.
func StringSliceToStructSlice[T any](in []string) ([]T, error) {
	if len(in) == 0 {
		return nil, nil
	}

	out := make([]T, len(in))
	for i := range in {
		v, err := JsonOrYamlToStruct[T]([]byte(in[i]))
		if err != nil {
			return nil, fmt.Errorf("decoding element %d: %w", i, err)
		}

		out[i] = v
	}

	return out, nil
}

// GetFuncNameByTypeNames returns the name of the adaptor function that converts
// from typeNameIn to typeNameOut, or an empty string if no built-in adaptor
// exists for that pair. Integer, unsigned, and float types are matched by
// family (e.g. any "intN" maps to the same adaptor).
func GetFuncNameByTypeNames(typeNameIn, typeNameOut string) string {
	funcMap := map[string]map[string]string{
		"net.IP": {
			"string": "IPToString",
		},
		"string": {
			"net.IP":        "StringToIP",
			"time.Time":     "StringToTime",
			"time.Duration": "StringToDuration",
			"net.IPNet":     "StringToIPNet",
			"bool":          "StringToBool",
			"int*":          "StringToInteger",
			"uint*":         "StringToInteger",
			"float*":        "StringToFloat",
		},
		"time.Time": {
			"string": "TimeToString",
		},
		"time.Duration": {
			"string": "DurationToString",
		},
		"net.IPNet": {
			"string": "IPNetToString",
		},
		"bool": {
			"string": "BoolToString",
			"int*":   "BoolToInteger",
			"uint*":  "BoolToInteger",
		},
		"int*": {
			"string": "IntegerToString",
			"int*":   "IntegerToInteger",
			"uint*":  "IntegerToInteger",
			"float*": "IntegerToFloat",
		},
		"uint*": {
			"string": "IntegerToString",
			"int*":   "IntegerToInteger",
			"uint*":  "IntegerToInteger",
			"float*": "IntegerToFloat",
		},
		"float*": {
			"string": "FloatToString",
			"float*": "FloatToFloat",
			"int*":   "FloatToInteger",
			"uint*":  "FloatToInteger",
		},
	}

	inMap, ok := funcMap[convertToWildcardType(typeNameIn)]
	if !ok {
		return ""
	}

	funcName, ok := inMap[convertToWildcardType(typeNameOut)]
	if !ok {
		return ""
	}

	return funcName
}

func convertToWildcardType(typeName string) string {
	if regexp.MustCompile("int(|[0-9]+)").MatchString(typeName) {
		return "int*"
	}

	if regexp.MustCompile("uint(|[0-9]+)").MatchString(typeName) {
		return "uint*"
	}

	if regexp.MustCompile("float(|[0-9]+)").MatchString(typeName) {
		return "float*"
	}

	return typeName
}
